# Generated by Django 5.2.6 on 2025-09-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=60)),
                ('year', models.FloatField()),
            ],
        ),
    ]
